# Test call of reusable workflow
name: Test Android Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
      # TODO - remove on merge
      - feat/android-build-action
jobs:
  android_build:
    # TODO - Replace with main on merge
    uses: supportingami/programming-club-builder/.github/workflows/android-build.yml@feat/android-build-action
    with:
      dist-path: demo
