# Reusable action to generate an android app from another repo
# containing bundled web code
name: Android Build
on:
  workflow_call:
    inputs:
      dist-path:
        description: path to folder containing code to include in app. Omit if code not in a subfolder
        type: string
      icon-path:
        description: path to a png image image to use for android icon
        type: string
      app-name:
        description: name of app to display on android device
        type: string
        default: Programming Club
      app-id:
        description: identifier of app for use on android device
        type: string
        default: club.programming.app
jobs:
  android_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout app builder code
        uses: actions/checkout@v4
        with:
          repository: "supportingami/programming-club-builder"
          ref: main

      - name: Checkout app repo code
        uses: actions/checkout@v4
        with:
          path: "dist"
          sparse-checkout: ${{ inputs.dist-path }}
          sparse-checkout-cone-mode: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      # Install required 3rd-party dependencies. Use 'ci' command to ensure install consistent
      - name: Install dependencies
        run: npm ci

      # If the exernal repo code is already in a folder, e.g. `build/index.html`, then it will be populated
      # with the extra top-level folder, `dist/build/index.html`. Move all subfolder files one level higher
      - name: Move repo code in nested folder
        if: ${{ inputs.dist-path }}
        run: mv  dist/${{ inputs.dist-path }}/* dist

      - name: Add app icon
        if: ${{ inputs.icon-path }}
        run: |
          mkdir assets
          cp  dist/${{ inputs.icon-path }} assets/icon.png 
          npx capacitor-assets generate --android

      - name: Update capacitor config
        uses: restackio/update-json-file-action@2.1
        with:
          file: capacitor.config.json
          fields: '{"appId": "${{inputs.app-id}}", "appName": "${{inputs.app-name}}"}'

      - name: Add android platform
        run: npx cap add android

      - name: Sync Capacitor
        run: npx cap sync

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build Android Debug APK
        working-directory: ./android
        run: ./gradlew :app:assembleDebug

      - name: Upload Debug Bundle
        uses: actions/upload-artifact@v4
        with:
          name: android
          path: ./android/app/build/outputs/apk/debug/app-debug.apk
