# Create android release AAB
name: Android - Build
on:
  workflow_call:
    inputs:
      dist-path:
        description: path to folder containing code to include in app. Omit if code not in a subfolder
        type: string
        default: ""
jobs:
  android_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout app builder code
        uses: actions/checkout@v4
        with:
          repository: "supportingami/programming-club-builder"
          ref: feat/android-build-workflows

      - name: Checkout app repo code
        uses: actions/checkout@v4
        with:
          path: "dist"
          sparse-checkout: ${{ inputs.dist-path }}
          sparse-checkout-cone-mode: false

      - name: Debug checkout files
        run: |
          echo(ls)
          echo(ls dist)

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      # Install required 3rd-party dependencies. Use 'ci' command to ensure install consistent
      - name: Install dependencies
        run: npm ci

      # TODO - generate assets
      # TODO - allow capacitor overrides
      - name: Add android platform
        run: npx cap add android

        # Re-sync as remote cache won't populate files during nx build command
      - name: Sync Capacitor
        run: npx cap sync

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Build Android Debug Bundle
        working-directory: ./android
        run: ./gradlew :app:assembleDebug

      - name: Upload Debug Bundle
        uses: actions/upload-artifact@v4
        with:
          name: debug_aab
          path: ./android/app/build/outputs/bundle/debug/app-debug.aab

      # - name: Build Android Release Bundle
      #   working-directory: ./android
      #   run: ./gradlew :app:bundleRelease
