# Test call of reusable workflow
name: Test Android Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feat/android-build-workflows
jobs:
  android_build:
    uses: supportingami/programming-club-builder/.github/workflows/android-build.yml@feat/android-build-workflows
    with:
      dist-path: demo
