name: Demo Android Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  android_build:
    uses: supportingami/programming-club-builder/.github/workflows/android-build.yml@main
    with:
      dist-path: demo
      icon-path: logo.png
      app-name: Programming Club Demo
      app-id: club.programming.app
